index:
    path: /
    controller: App\Controller\HomeController::index

check_scrybe_status:
    path: /refresh_status/{userfileId}
    controller: App\Controller\ConnectionController::refreshStatus

show_scrybed_results:
    path: /show_results/{userfileId}
    controller: App\Controller\ConnectionController::saveResults

edit_scribed_text:
      path: /edit_scribed_text/{userfileId}
      controller: App\Controller\TextEditorController::textEditor

media_player:
    path: /audio_files/{userfileId}
    controller: App\Controller\MediaController::mediaPlayer

secure_login:
    path: /login
    controller: App\Controller\SecurityController::login
    methods: GET|POST

register:
    path: /register
    controller: App\Controller\RegistrationController::register

app_logout:
    path: /logout
    methods: GET

user_dashboard:
    path: /user_dashboard
    controller: App\Controller\UserDashboardController::showTranscriptions

about:
    path: /about
    controller: App\Controller\HomeController::about
    methods: GET

pricing:
    path: /pricing
    controller: App\Controller\PricingController::pricing

buy:
    path: /buy/{hours}
    controller: App\Controller\PricingController::buyHours
    methods: GET

bought:
    path: /bought/{hours}
    controller: App\Controller\PricingController::updateCredits
    methods: GET

editor:
    path: /editor
    controller: App\Controller\HomeController::editor

upload:
    path: /upload
    controller: App\Controller\HomeController::upload

send_with_api:
    path: /process_scrybe/{userfileId}
    controller: App\Controller\ConnectionController::processScrybeFile

export_txt:
    path: /export/txt/{userfileId}
    controller: App\Controller\ExportController::exportTxt

export_subtitles:
    path: /export/srt/{userfileId}
    controller: App\Controller\ExportController::exportSrt

restore_file:
    path: /reset_file/{userfileId}
    controller: App\Controller\UserDashboardController::resetUserfile

delete_file:
    path: /remove_file/{userfileId}
    controller: App\Controller\UserDashboardController::deleteUserfile

check_transcription_status:
    path: /check_status/{userfileId}
    controller: App\Controller\ConnectionController::checkTranscriptionStatus
    methods: GET

#download_transcribed_text:
#  path: /download_transcribed_text
#  controller: App\Controller\TextEditorController::downloadTranscribedText
#
#save_transcribed_text:
#  path: /save_transcribed_text
#  controller: App\Controller\TextEditorController::saveTranscribedText
