index:
    path: /
    controller: App\Controller\HomeController::index

demo:
    path: /demo
    controller: App\Controller\ConnectionController::showStaticFileUploadPage

send_demo_file:
    path: /send_demo_file
    controller: App\Controller\ConnectionController::sendDemoFile

check_scrybe_status:
    path: /refresh_status/{userfileId}
    controller: App\Controller\ConnectionController::refreshStatus

show_scrybed_results:
    path: /show_results/{userfileId}
    controller: App\Controller\ConnectionController::showResults

download_txt_file:
    path: /download_txt_file/{jobId}
    controller: App\Controller\ConnectionController::DownloadTxtFile

edit_scribed_text:
      path: /edit_scribed_text/{userfileId}
      controller: App\Controller\TextEditorController::textEditor

media_player:
    path: /public/audio_files/demo/{file}
    controller: App\Controller\TextEditorController::mediaPlayer

secure_login:
    path: /login
    controller: App\Controller\SecurityController::login
    methods: GET|POST

register:
    path: /register
    controller: App\Controller\RegistrationController::register

app_logout:
    path: /logout
    methods: GET

user_dashboard:
    path: /user_dashboard
    controller: App\Controller\UserDashboardController::showTranscriptions

about:
    path: /about
    controller: App\Controller\HomeController::about
    methods: GET

pricing:
    path: /pricing
    controller: App\Controller\PricingController::pricing

buy:
    path: /buy/{hours}
    controller: App\Controller\PricingController::buyHours
    methods: GET

bought:
    path: /bought/{hours}
    controller: App\Controller\PricingController::updateCredits
    methods: GET

editor:
    path: /editor
    controller: App\Controller\HomeController::editor

upload:
    path: /upload
    controller: App\Controller\HomeController::upload

send_with_api:
    path: /process_scrybe/{userfileId}
    controller: App\Controller\ConnectionController::processScrybeFile

check_transcription_status:
    path: /check_status/{userfileId}
    controller: App\Controller\ConnectionController::checkTranscriptionStatus
    methods: GET

#download_transcribed_text:
#  path: /download_transcribed_text
#  controller: App\Controller\TextEditorController::downloadTranscribedText
#
#save_transcribed_text:
#  path: /save_transcribed_text
#  controller: App\Controller\TextEditorController::saveTranscribedText
