index:
    path: /
    controller: App\Controller\HomeController::index

send_demo_file:
    path: /send_demo_file
    controller: App\Controller\ConnectionController::sendDemoFile

check_scrybe_status:
    path: /refresh_status/{jobId}
    controller: App\Controller\ConnectionController::refreshStatus

show_scrybed_results:
    path: /show_results/{jobId}
    controller: App\Controller\ConnectionController::showResults

download_txt_file:
    path: /download_txt_file/{jobId}
    controller: App\Controller\ConnectionController::DownloadTxtFile

edit_scribed_text:
      path: /edit_scribed_text/{job_id}
      controller: App\Controller\TextEditorController::textEditor

secure_login:
    path: /login
    controller: App\Controller\SecurityController::login
    methods: GET|POST

register:
    path: /register
    controller: App\Controller\RegistrationController::register

app_logout:
    path: /logout
    methods: GET

user_dashboard:
    path: /user_dashboard
    controller: App\Controller\UserDashboardController::showTranscriptions

about:
    path: /about
    controller: App\Controller\HomeController::about
    methods: GET

pricing:
    path: /pricing
    controller: App\Controller\HomeController::pricing

editor:
    path: /editor
    controller: App\Controller\HomeController::editor

upload:
    path: /upload
    controller: App\Controller\HomeController::upload

#download_transcribed_text:
#  path: /download_transcribed_text
#  controller: App\Controller\TextEditorController::downloadTranscribedText
#
#save_transcribed_text:
#  path: /save_transcribed_text
#  controller: App\Controller\TextEditorController::saveTranscribedText
